spring:
  application:
    name: serie-service
  config:
    import: configserver:http://localhost:8888
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test
      port: 27017
