server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mscatalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: msmovie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: msseries-service
          uri: lb://serie-service
          predicates:
            - Path=/api/v1/series/**
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway
