server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: serie-service
  rabbitmq:
   username: guest
   password: guest
   host: localhost
   port: 5672
  zipkin:
    baseUrl: http://localhost:9411/  


message: hello from serie-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
